from __future__ import annotations

import secrets

from pydantic import Field, field_validator
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    app_name: str = "Asset Maintenance MVP"
    environment: str = "development"
    database_url: str = "sqlite:///./app.db"

    # Generated by default for local development. In production provide a stable value via .env.
    secret_key: str = Field(default_factory=lambda: secrets.token_urlsafe(48), min_length=32)

    access_token_expire_minutes: int = Field(default=30, ge=5, le=120)
    refresh_token_expire_minutes: int = Field(default=1440, ge=60, le=43200)

    max_login_attempts: int = Field(default=5, ge=3, le=10)
    lockout_minutes: int = Field(default=15, ge=1, le=120)

    allowed_origins: list[str] = Field(default_factory=list)
    max_request_size_bytes: int = Field(default=1_000_000, ge=10_000, le=10_000_000)

    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        case_sensitive=False,
        extra="ignore",
    )

    @field_validator("allowed_origins", mode="before")
    @classmethod
    def parse_origins(cls, value: str | list[str] | None) -> list[str]:
        if value is None:
            return []
        if isinstance(value, str):
            return [item.strip() for item in value.split(",") if item.strip()]
        return value


settings = Settings()
