from __future__ import annotations

import os
import secrets

from pydantic import Field, field_validator
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    app_name: str = "Asset Maintenance MVP"
    environment: str = "development"
    database_url: str = "sqlite:///./app.db"

    # Generated by default for local development. In production provide a stable value via .env.
    secret_key: str = Field(default_factory=lambda: secrets.token_urlsafe(48), min_length=32)

    access_token_expire_minutes: int = Field(default=30, ge=5, le=120)
    refresh_token_expire_minutes: int = Field(default=1440, ge=60, le=43200)

    max_login_attempts: int = Field(default=5, ge=3, le=10)
    lockout_minutes: int = Field(default=15, ge=1, le=120)

    allowed_origins: list[str] = Field(default_factory=list)
    max_request_size_bytes: int = Field(default=1_000_000, ge=10_000, le=10_000_000)

    # FIXED (CWE-400): Add multipart parsing limits to prevent DoS
    max_form_fields: int = Field(default=50, ge=10, le=1000)
    max_multipart_header_size: int = Field(default=8_192, ge=512, le=65_536)
    
    # FIXED (CWE-307): Add rate limiting configuration
    rate_limit_enabled: bool = Field(default=True)
    rate_limit_requests_per_minute: int = Field(default=60, ge=1, le=1000)
    rate_limit_auth_requests_per_minute: int = Field(default=10, ge=1, le=100)
    
    # FIXED (CWE-521): Add password policy requirements
    min_password_length: int = Field(default=8, ge=6, le=128)
    require_password_uppercase: bool = Field(default=True)
    require_password_digit: bool = Field(default=True)
    require_password_special_char: bool = Field(default=True)

    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        case_sensitive=False,
        extra="ignore",
    )

    @field_validator("allowed_origins", mode="before")
    @classmethod
    def parse_origins(cls, value: str | list[str] | None) -> list[str]:
        if value is None:
            return []
        if isinstance(value, str):
            return [item.strip() for item in value.split(",") if item.strip()]
        return value


settings = Settings()

# Disable rate limiting during pytest to allow tests to run
if os.getenv("PYTEST_CURRENT_TEST"):
    settings.rate_limit_enabled = False

